#!/usr/bin/env ruby

MYSQL_DIR  = "/usr/local/var/mysql"
SOURCE_ZFS = "my_app/mysql"

branch_checkout = ARGV[2] == "1"
new_branch = `git branch | grep '*' | awk '{print $2}'`.chomp

if branch_checkout && new_branch !~ /\(no/
  system "mysql.server stop"

  if new_branch == "master"
    new_zfs = SOURCE_ZFS
  else
    new_zfs = "#{SOURCE_ZFS}-#{new_branch}"
  end

  timestamp = Time.now.strftime("%Y%m%d%H%M")

  unless system("zfs list | grep -q #{new_zfs}")
    puts "Creating #{new_zfs}"
    system "zfs snapshot #{SOURCE_ZFS}@#{timestamp}"
    system "zfs clone #{SOURCE_ZFS}@#{timestamp} #{new_zfs}"
  end

  puts "Symlinking #{MYSQL_DIR} to /Volumes/#{new_zfs}"
  File.unlink MYSQL_DIR
  File.symlink "/Volumes/#{new_zfs}", MYSQL_DIR

  system "mysql.server start"
end
